#! /bin/bash

# Copyright (C) 2013 Jacob Müller
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## USER DEFINED VARIABLES ###############################################

# Path to the root directory of the local CyanogenMod source code
cmDir=/path/to/cm/source/code

#########################################################################


# Get processor architecture
if [ %PROCESSOR_ARCHITECTURE% == x86 ]; then
    cpuArch=32
else
    cpuArch=64
fi

# Get Ubuntu version
. /etc/lsb-release
ubuntuVers=$DISTRIB_RELEASE

# Build path to Translation Tools binary
ttPath=${cmDir}/tools/TranslationTools/binary/translationtools_${ubuntuVers}_x${cpuArch}

# Check if Translation Tools are installed
if [ -e $ttPath ]; then
    nohup $ttPath >/dev/null 2>&1&
else
    echo "Translation Tools aren't installed or are installed in a wrong directory"
fi
